### ISSUE TITLE
Meta data Issues

### ISSUE THREAD

**Issue by blasten** [PolymerElements/app-layout#196]
Let's get ready to land app-layout in the catalog:

* [x] bower.json needs a `"description"`
* [x] Remove links such as https://github.com/PolymerLabs/app-layout/blob/master/app-header/app-header.html#L152 from the doc comments.
* [x] Specify the name for each demo and also rename the files. (will also fix https://github.com/PolymerLabs/app-layout/issues/194) e.g. Similar to: https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L142-L149
* [x] Add the group and name annotation to each element.
* [ ] (cool to have) Consider a hero image for https://elements.polymer-project.org/browse?package=gold-elements&view=cards
* [x] bump the version to `0.9`
* [x] move to PolymerElements

**Comment by abdonrd** [comment]
In the catalog will be a single `app-layout` element?

**Comment by abdonrd** [comment]
And no need to move to PolymerElements organization?

**Comment by blasten** [comment]
Yeah, we are moving app-layout to PolymerElements
